## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-


def build(bld):
    module = bld.create_ns3_module('point-to-point-coalescing', ['network', 'mpi'])
    module.source = [
        'model/point-to-point-coalescing-net-device.cc',
        'model/point-to-point-coalescing-channel.cc',
        'model/point-to-point-coalescing-remote-channel.cc',
        'model/ppp-header-coalescing.cc',
        'helper/point-to-point-coalescing-helper.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'point-to-point-coalescing'
    headers.source = [
        'model/point-to-point-coalescing-net-device.h',
        'model/point-to-point-coalescing-channel.h',
        'model/point-to-point-coalescing-remote-channel.h',
        'model/ppp-header-coalescing.h',
        'helper/point-to-point-coalescing-helper.h',
        ]

    bld.ns3_python_bindings()
